### ISSUE TITLE
Change $@ to "$@"

### ISSUE THREAD

**Issue by hlovdal** [traderinteractive/tol-api-php#51]
The last line of tests/provisioning/set-env.sh is

```shell
$@
```

which will work fine as long as none of the arguments contain spaces in them. However the failsafe and correct way is to use `"$@"` which will handle embedded spaces correctly, and while at it you might add an exec as well:

```shell
exec "$@"
```

**Comment by chrisryan** [comment]
Fixed in PR #53. Thank you for the suggestion.
